### ISSUE TITLE
strip_prefix() is only work with unstable

### ISSUE THREAD

**Issue by eribol** [eignnx/tide-naive-static-files#4]
I tried to use this crate for serve static files but it gives error.

```method not found in tide::server::route::Route<_, tera::Tera>```

and when i googled it, i found that strip_prefix is working with only unstable.

**Comment by eignnx** [comment]
Hi @eribol! Yes `tide-naive-static-files` does depend on some of `tide`'s unstable features like `strip_prefix`.

I think one way to solve your problem would be for you to also depend on `tide`'s unstable features. This would **not** require you to use the unstable rust compiler though. You would just have to change your `Cargo.toml` from something like this:

```toml
[dependencies]
tide = "0.6.0"
```

to something like this:

```toml
[dependencies]
tide = { version = "0.6.0", features  = ["unstable"] }
```

Do you think that would work for you? I probably need to update this crate to version `tide` 0.6.0 anyway, so in the process I might be able to make a few changes if needed.
